mssql:
    deployment: 
        name: "helm-sqlserver-deployment"
        replicaCount: 1
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        pullPolicy: "IfNotPresent"
        podLabel: "helm-people-db"
        volumeName: "helm-people-db-volumes"
    service:
        name: "helm-sqlserver-service"
        portName: "helm-people-db-service-port"
        exposedPort: 14335
    persistentVolume:
        name: "helm-sqlserver-persistent-volume"
        hostPath: "/D/temp"
        capacity: "20Gi"
    persistentVolumeClaim:
        name: "helm-sqlserver-persistent-volume-claim"
    test:
        podName: "sqlserver-test-pod"
        image: "mcr.microsoft.com/mssql-tools"
