# Default values for people-api-database.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server:2019-latest
  sqlToolRepository: "mcr.microsoft.com/mssql-tools"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 1433

ingress:
  enabled: false

database:
  password: P@ssword
  persistentVolume:
    hostPath: "/E/temp"
    capacity: "20Gi"