apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mssql.deployment.name }}
spec:
  replicas: {{ .Values.mssql.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mssql.deployment.podLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.mssql.deployment.podLabel }}
    spec:
      containers:
        - image: {{ .Values.mssql.deployment.image }}
          name: {{ .Values.mssql.deployment.podLabel }}
          env:
          - name:  ACCEPT_EULA
            value:  "Y"
          - name:  SA_PASSWORD
            value:  "P@ssw0rd123"
          imagePullPolicy: {{ .Values.mssql.deployment.pullPolicy }}
          ports:
          - containerPort: 1433
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: {{ .Values.mssql.deployment.volumeName }}
      volumes:
      - name: {{ .Values.mssql.deployment.volumeName }}
        persistentVolumeClaim:
            claimName: {{ .Values.mssql.persistentVolumeClaim.name }}