apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mssql.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.mssql.persistentVolume.capacity }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: {{ .Values.mssql.persistentVolume.hostPath }}
    type: Directory