apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mssql.persistentVolumeClaim.name }}
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mssql.persistentVolume.capacity }}