apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    # we specify, to which Pods the Service should forward the traffic
    app: k8s-people-api
  ports:
    - name: k8s-people-api-service-port
      port: 5003 # SERVICE_PORT - port exposed by this service
      targetPort: 80 # Pod's port number (Pod is targeted by the Service)