apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.projectName }}-service
spec:
  type: LoadBalancer
  selector:
    # we specify, to which Pods the Service should forward the traffic
    app: {{ .Values.global.projectName }}-pod
  ports:
    - name: {{ .Values.simpleapi.service.portName }}
      port: {{ .Values.simpleapi.service.exposedPort }} # SERVICE_PORT - port exposed by this service
      targetPort: 80 # Pod's port number (Pod is targeted by the Service)